# CLASS-2

In [1]:
import random
import numpy as np

In [9]:
a = np.arange(10)
b = np.array([22,33,44,55,11])

In [10]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
a.ndim

1

In [11]:
print(b)

[22 33 44 55 11]


In [8]:
?a.reshape

In [15]:
c = a.reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
c.ndim

2

## resize

In [18]:
d = np.arange(10,15)
d.resize(8,)# we can not store an array during resize bcz its referencing original array d
d

array([10, 11, 12, 13, 14,  0,  0,  0])

In [19]:
e = np.arange(10,15)
f = e
f.resize(8,)# we can not store an array during resize bcz its referencing original array d
f

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [21]:
g = np.arange(10,15)
h = g.copy() # create a copy and then can resize
h.resize(4,2)
h

array([[10, 11],
       [12, 13],
       [14,  0],
       [ 0,  0]])

In [22]:
h.ndim

2

In [23]:
array1 = np.arange(10,15)
array2 = np.resize(array1,(4,2))
array2

array([[10, 11],
       [12, 13],
       [14, 10],
       [11, 12]])

array([10, 11, 12, 13, 14, 10, 11, 12])

In [27]:
array1 = np.arange(10,15)
array1.resize((8,))
array1

array([10, 11, 12, 13, 14,  0,  0,  0])

In [28]:
array1 = np.arange(10,15)
array2 = np.resize(array1,(8,))
array2

array([10, 11, 12, 13, 14, 10, 11, 12])

# np.ravel()

In [29]:
#any dimension of th array can be converted into single dimension
array1 = np.array([np.arange(2,7), np.arange(15,20)])
array1

array([[ 2,  3,  4,  5,  6],
       [15, 16, 17, 18, 19]])

In [30]:
array1.ravel()

array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19])

In [31]:
array2 = np.array([np.arange(2,7), np.arange(15,20)])
array2

array([[ 2,  3,  4,  5,  6],
       [15, 16, 17, 18, 19]])

# flatten()

In [34]:
array2.flatten()

array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19])

In [36]:
#adding a new dimension

array1 = np.array([22,33,44])
array1.shape

(3,)

In [37]:
array2 = array1[:,np.newaxis]
array2

array([[22],
       [33],
       [44]])

In [38]:
array2.ndim

2

In [39]:
array3 = array2[:,np.newaxis]
array3

array([[[22]],

       [[33]],

       [[44]]])

In [40]:
array3.ndim

3

In [42]:
array4 = array3[:,np.newaxis]
array4

array([[[[22]]],


       [[[33]]],


       [[[44]]]])

In [43]:
array4.ndim

4

In [44]:
array4.shape

(3, 1, 1, 1)

# ------------------------------

# Array Sort

In [45]:
array1 = np.array([[4,5,2],[3,2,1]])
array1.sort(axis=1) #sorted rowwise
array1

array([[2, 4, 5],
       [1, 2, 3]])

In [46]:
array1 = np.array([[4,5,2],[3,2,1]])
array1.sort(axis=0) #sorted columnwise
array1

array([[3, 2, 1],
       [4, 5, 2]])

## Reduction & statistical operation

In [48]:
array1 = np.arange(2,6)
array1.prod()

120

In [55]:
array1 = np.array([np.arange(2,6),np.arange(2,6)])
prod = np.prod(array1,axis = 1)#columnwise reduction
prod

array([120, 120])

In [57]:
array1 = np.array([np.arange(2,6),np.arange(2,6)])
prod = np.prod(array1,axis = 0)#rowwise reductionn
prod

array([ 4,  9, 16, 25])

In [58]:
prod.sum()

54

In [59]:
prod.mean()

13.5

In [68]:
prod.std()

7.88986691902975