# NUMPY

In [1]:
import numpy as np

In [2]:
#create single dimensional array
array_1 = np.array([11,22,33])#accept only homoginuous datatype
array_1

array([11, 22, 33])

In [4]:
#create 2 dimensional array
array_2 = np.array([[11,22,33],[21,22,33]])
array_2

array([[11, 22, 33],
       [21, 22, 33]])

In [5]:
#check the shape
array_2.shape

(2, 3)

In [6]:
#check the array dimension
array_2.ndim

2

In [7]:
array_1.ndim

1

In [8]:
#creating a array using arrange function
array_3 = np.arange(5)
array_3

array([0, 1, 2, 3, 4])

In [9]:
array_4 = np.arange(5,20,5)
array_4

array([ 5, 10, 15])

# LINSPACE function

In [10]:
#all are linearly space number
array_4 = np.linspace(0,1,10)
array_4

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
##ones
array_5 = np.ones((2,3))
array_5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#zeros
array_6 = np.zeros((3,3))
array_6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#identity matrix
array_7 = np.eye(4)
array_7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#np.diag
array_8 = np.diag((1,2,3,4))
array_8

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
##create a random number
array_9 = np.random.rand(4)
array_9

array([0.08203323, 0.97338889, 0.06525836, 0.67101355])

In [1]:
import numpy as np
#genarate 2*2 array
array_10 = np.random.rand(4,2,5)
array_10

array([[[0.88581785, 0.96320854, 0.68236617, 0.90930556, 0.1282715 ],
        [0.39959243, 0.70079203, 0.3014579 , 0.58405525, 0.8876818 ]],

       [[0.44102105, 0.02809969, 0.72419725, 0.58834713, 0.34341766],
        [0.9032941 , 0.76174078, 0.20305842, 0.99493266, 0.54236562]],

       [[0.00929372, 0.60315633, 0.96805585, 0.38738187, 0.75180712],
        [0.75968689, 0.73548739, 0.23510585, 0.13354504, 0.68224081]],

       [[0.787204  , 0.95788715, 0.5064759 , 0.63907546, 0.67726236],
        [0.31145811, 0.22352623, 0.32012371, 0.27565127, 0.04525338]]])

In [22]:
#normally distributed number generate
array_11 = np.random.randn(5)
array_11

array([ 0.88564801,  0.207339  ,  0.15994496, -1.21535571, -0.19223808])

In [2]:
array_11 = np.random.randn(3,2,5)
array_11

array([[[-0.32834583,  1.58327018, -0.53425828,  0.95814503,
         -0.77953871],
        [ 0.28259302, -0.51849423, -0.67722239,  0.34150718,
         -1.09415505]],

       [[ 0.413115  ,  1.32156511,  1.87754866,  0.7793437 ,
         -0.92071015],
        [ 0.08275869, -0.81779564, -0.64159933, -1.48282922,
         -0.52490844]],

       [[ 0.56712193, -1.46570436, -0.57397363, -0.20431356,
         -0.3149435 ],
        [-2.15845699,  1.20049918,  0.71545405,  0.38758245,
          0.97616322]]])

In [23]:
#help
?np.random.randn


In [24]:
#creating a empty array
empty_array = np.empty((4,3))
empty_array

array([[6.23042070e-307, 1.89146896e-307, 1.33511018e-306],
       [1.78022342e-306, 6.89810244e-307, 1.02360935e-306],
       [1.29061685e-306, 6.23055651e-307, 8.90104239e-307],
       [6.11908893e-308, 1.29062229e-306, 7.23188050e-308]])

In [1]:
import numpy as np
arr_13 = np.empty((4,3))
arr_13

array([[4.45057637e-308, 1.78021527e-306, 8.45549797e-307],
       [1.37962049e-306, 1.11260619e-306, 1.78010255e-306],
       [9.79054228e-307, 4.45057637e-308, 8.45596650e-307],
       [9.34602321e-307, 4.94065646e-322, 1.42404727e-306]])

In [3]:
#check numpy version
np.__version__

'1.15.4'

In [3]:
np.empty([2,2])

array([[0.00000000e+000, 6.95177921e-310],
       [9.88131292e-324,             nan]])

In [4]:
#np.tile
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [14]:
#repetation of array
b = np.array([[1, 2],[4,3]])
x = np.tile(b, 3)
x

array([[1, 2, 1, 2, 1, 2],
       [4, 3, 4, 3, 4, 3]])

In [17]:
x[1][5]

3

In [3]:
array_2 = np.array([[11,22,33],[21,20,35],[78,54,32]])
array_2

array([[11, 22, 33],
       [21, 20, 35],
       [78, 54, 32]])

In [27]:
array_2[:2,1:]

array([[22, 33],
       [20, 35]])

In [49]:
array_2[0:2]

array([[11, 22, 33],
       [21, 20, 35]])

In [42]:
array_2[0][:2]

array([11, 22])

# -----------------------------------------------------------------------------------------------------------

In [26]:
#Numpy data type
arr_1 = np.array([4,-2,5,9],dtype=float)
arr_1

array([ 4., -2.,  5.,  9.])

In [27]:
arr_1.dtype

dtype('float64')

In [28]:
arr_2 = np.array([4,-2,5,9],dtype=int)
arr_2

array([ 4, -2,  5,  9])

In [29]:
arr_2.dtype

dtype('int32')

In [30]:
arr_3 = np.array(["hello","how","are","you"])#always give the length of longest string
arr_3

array(['hello', 'how', 'are', 'you'], dtype='<U5')

In [31]:
arr_4 = np.array([True,False])
arr_4.dtype

dtype('bool')

In [3]:
arr_5 = np.array([1,-4,5,6.5])
arr_5.dtype

dtype('float64')

In [8]:
 k = arr_5.astype(int)
k

array([ 1, -4,  5,  6])

In [6]:
k.dtype

dtype('int32')

-------------------------

In [10]:
#numpy indexing and slicing
k[::-1]

array([ 6,  5, -4,  1])

In [11]:
array1 = np.arange(6)
array1

array([0, 1, 2, 3, 4, 5])

In [12]:
array1[0]

0

In [13]:
array1[-1]

5

In [14]:
array2 = np.array([[4,3],[3,5],[1,2]])
array2

array([[4, 3],
       [3, 5],
       [1, 2]])

In [15]:
array2[2,1]

2

In [17]:
#modifying value
array2[2,1]=-3
array2

array([[ 4,  3],
       [ 3,  5],
       [ 1, -3]])

In [18]:
#retrive the first row
array2[2]

array([ 1, -3])

In [19]:
#retrive 2nd row and col
array2[2,:]

array([ 1, -3])

In [21]:
#retrive column
array2[:,1]

array([ 3,  5, -3])

In [24]:
array2[:,0]

array([4, 3, 1])

In [25]:
array2

array([[ 4,  3],
       [ 3,  5],
       [ 1, -3]])

In [28]:
array2[1:3,]

array([[ 3,  5],
       [ 1, -3]])

In [29]:
arr_1 = 2* np.arange(10)
arr_1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
arr_1[0:6:2]

array([0, 4, 8])

In [37]:
#putting all value from 3rd index 1
arr_1[3:] = np.ones(7)
arr_1

array([0, 2, 4, 1, 1, 1, 1, 1, 1, 1])

In [38]:
#filter
import random
rand = np.random.randint(25,50,5)
rand

array([41, 30, 30, 37, 25])

In [40]:
np.random.seed(50)#this seed will fix the no wont be random agian if you run 1000 times also
rand = np.random.randint(25,50,5)
rand

array([41, 25, 36, 38, 26])

In [41]:
arr = (rand % 2 == 0)
arr

array([False, False,  True,  True,  True])

In [42]:
#to get back the array we need pass that stored boolean
rand[arr]

array([36, 38, 26])

In [50]:
arr_country = np.array(["INDIA","RASSIA","FRANCE"," "])
arr_country

array(['INDIA', 'RASSIA', 'FRANCE', ' '], dtype='<U6')

In [52]:
arr_country[arr_country == " "]="PAKISTAN"
arr_country

array(['INDIA', 'RASSIA', 'FRANCE', 'PAKIST'], dtype='<U6')

# complex indexing

In [57]:
arr_14 = np.arange(-1,-20,-1)[::-1][::-1][::-1][::-1][::-1][::-1][::-1][::-1][::-1][::-1][::-1][::-1][::-1][::-1]
arr_14

array([ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13,
       -14, -15, -16, -17, -18, -19])

# ==============================================================

# copy() view()

In [58]:
var = np.arange(5)
var

array([0, 1, 2, 3, 4])

In [59]:
arr2 = var[::2]
arr2

array([0, 2, 4])

In [60]:
arr2[1] = -4#it will modify original too
arr2

array([ 0, -4,  4])

In [61]:
var#original value get modified

array([ 0,  1, -4,  3,  4])

In [62]:
#how not to change the original with copy
var1 = np.arange(10)
var1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr3 = var1[:3].copy()
arr3

array([0, 1, 2])

In [65]:
arr3[0]=1
arr3

array([1, 1, 2])

In [66]:
var1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

-----------------------------

In [7]:
#basic operations

arpan = np.arange(1,10) * 4
arpan

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [6]:
arpan2 = np.arange(1,10)**2
arpan2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [72]:
arpan3 = arpan * 0.5
arpan3

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [73]:
arpan4 = 3+np.arange(0,20,2)
arpan4

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [74]:
#2 arrays multiplication
arpan2*arpan3

array([   2.,   16.,   54.,  128.,  250.,  432.,  686., 1024., 1458.])

In [75]:
arpan2/arpan3

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [76]:
arpan4 = np.arange(100)
%timeit arpan4*3

956 ns ± 8.43 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [4]:
arpan5 =range(100)
%timeit [arpan5[i] **3 for i in arpan5]

60.1 µs ± 1.02 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [5]:
#matrix multiplication
import numpy as np
arpan6 = np.array([[5,2],[6,3]])
arpan7 = np.array([[2,3],[4,5]])
arpan8 = arpan6.dot(arpan7)
arpan8

array([[18, 25],
       [24, 33]])

In [8]:
#array comparison
arpan>arpan2

array([ True,  True,  True, False, False, False, False, False, False])

In [10]:
arpan10 = np.array([True,False,True,False])
arpan11 = np.array([True,True,False,True])

arpan20 = np.logical_and(arpan10,arpan11)
arpan20

array([ True, False, False, False])

In [13]:
k=arpan10&arpan11
k

array([ True, False, False, False])

In [14]:
np.pi

3.141592653589793

In [16]:
np.sin(np.pi)

1.2246467991473532e-16

In [19]:
#different shape can not be add without using broadcasting
a = np.arange(1,6)
b = np.arange(1,8)
a+b

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

# broadcasting11

In [22]:
a = np.arange(1,6)
b = np.arange(1,8)
c = np.array_equal(a,b)
c

False

In [25]:
print(np.any(a>b))#any will return true if one of them returns true
print(np.all(a==b))

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [50]:
array_2

array([[11, 22, 33],
       [21, 20, 35],
       [78, 54, 32]])

In [51]:
x=np.array([1,2,3])
array_2 + x

array([[12, 24, 36],
       [22, 22, 38],
       [79, 56, 35]])

In [52]:
array_2*x

array([[ 11,  44,  99],
       [ 21,  40, 105],
       [ 78, 108,  96]])

In [26]:
#how to broadcast

arpan90 = np.ones([5,2])
arpan90

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
arpan91 = np.array([5,2])
arpan91

array([5, 2])

In [28]:
#broadcasting
arpan92 = arpan90+arpan91
arpan92

array([[6., 3.],
       [6., 3.],
       [6., 3.],
       [6., 3.],
       [6., 3.]])

In [29]:
arpan93 = np.array([[11,22,33]])
arpan94 = arpan93.T
arpan94

array([[11],
       [22],
       [33]])

In [30]:
arpan95 = arpan93+arpan94
arpan95

array([[22, 33, 44],
       [33, 44, 55],
       [44, 55, 66]])

In [32]:
for i in np.linspace(0,1,10):
    print(i)

0.0
0.1111111111111111
0.2222222222222222
0.3333333333333333
0.4444444444444444
0.5555555555555556
0.6666666666666666
0.7777777777777777
0.8888888888888888
1.0


In [39]:
d = np.arange(2,3)
d

array([2])

In [38]:
d.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [40]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [41]:
xx = x.reshape(4,1)
xx

array([[0],
       [1],
       [2],
       [3]])

In [43]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [44]:
z=np.ones((3,4))
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
x1 = xx + y
x1

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])