In [12]:
import numpy as np
##1 dimensional array

array_1=np.array([11,22,33])
print(array_1)

[11 22 33]


In [13]:
##2 dimensional array

array_2 = np.array([[11,22,33],[21,22,23]])
print(array_2)

[[11 22 33]
 [21 22 23]]


In [30]:
#Shape of the array

array_2.shape

(2, 3)

In [31]:
#dimension of the array
print(array_1.ndim)
array_2.ndim

1


2

In [32]:
#creating array using arange function

array_3=np.arange(5)
array_3

array([0, 1, 2, 3, 4])

In [33]:
#arange in a limit

array_31= np.arange(5,10)
array_31

array([5, 6, 7, 8, 9])

In [34]:
array_31 = np.arange(5,20,5)  #arange(startindex, stopindex, stepvalue)
array_31

array([ 5, 10, 15])

# LINSPACE FUNCTION

In [35]:
#creating array using np.linspace

array_4 = np.linspace(0,1,10) #linearly spaced array from 0-1
print(array_4)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [36]:
#creating a 2x3 array of one using np.ones

array_5=np.ones((2,3))
array_5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
#np.zeroes  zero matrix

array_51=np.zeros((5,3))
array_51

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#np.eye  identity matrix

array_11=np.eye(4)
array_11

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
#np.diag  diagonal matrix

array_7=np.diag((1,2,3,4))
array_7

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [40]:
array_7=np.diag((9,4,5,6))
array_7

array([[9, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [41]:
##np.random generating random numbers

array_8=np.random.rand(10) #random.rand  generation
array_8

array([0.45243004, 0.92952316, 0.572093  , 0.29234574, 0.24486964,
       0.4789853 , 0.68293886, 0.34737416, 0.81084384, 0.62937103])

In [42]:
array_8=np.random.rand(4) #random.rand  generation
array_8

array([0.39321723, 0.21104281, 0.28998382, 0.83546237])

In [43]:
array_8=np.random.rand(4,2) #random.rand  generation for 2x2 array
array_8

array([[0.61963296, 0.51073292],
       [0.15881374, 0.81568542],
       [0.9374224 , 0.66968443],
       [0.71275567, 0.89436562]])

In [44]:
array_8 = np.random.rand(4,3)
print(array_8)

[[0.90288362 0.88798003 0.40646672]
 [0.90931742 0.23779581 0.02464481]
 [0.31371467 0.68717691 0.90687048]
 [0.5802203  0.04408143 0.80202457]]


In [45]:
#random number generation with normal distribution
#each time the numbers that are generated
array_9 = np.random.randn(5)
array_9

array([ 1.12762956, -1.24295921, -0.5731421 , -1.1372566 , -0.09175475])

In [ ]:
help(np.random.randn())

In [ ]:
#Gives the info the function
?np.random.randn

In [46]:
##np.empty creating an uninitialized array

array_10=np.empty((4,3))
array_10

array([[0.90288362, 0.88798003, 0.40646672],
       [0.90931742, 0.23779581, 0.02464481],
       [0.31371467, 0.68717691, 0.90687048],
       [0.5802203 , 0.04408143, 0.80202457]])

In [ ]:
?np.empty

In [47]:
##np.tile Repeats the values for the required number

array_11=np.tile(([5,3],[8,9]),3)
array_11

array([[5, 3, 5, 3, 5, 3],
       [8, 9, 8, 9, 8, 9]])

In [48]:
array_12=np.tile(np.array([[5,3],[8,9]]),3)
array_12

array([[5, 3, 5, 3, 5, 3],
       [8, 9, 8, 9, 8, 9]])

# NumPy Datatypes

In [14]:
#Default datatype is float

arr_1=np.array([4,-2,5,9],dtype=float)
arr_1

array([ 4., -2.,  5.,  9.])

In [50]:
arr_1.dtype

dtype('float64')

In [51]:
arr_1=np.array([4,2,-9,8])
arr_1.dtype

dtype('int32')

In [52]:
arr_1=np.array([4,2,-9,8], dtype=int)
arr_1

array([ 4,  2, -9,  8])

In [15]:
arr_3 = np.array(['hello','hi','how are you'])
arr_3.dtype #Displays the type and length of the string

dtype('<U11')

In [54]:
array_5=np.array([True, False])
array_5.dtype

dtype('bool')

In [55]:
#Typecasting

arr_6=np.array([1,-4,5,6.32])
arr_6.dtype

dtype('float64')

In [56]:
arr_6=arr_6.astype(int)

In [57]:
arr_6.dtype

dtype('int32')

In [58]:
arrayint=np.array([1,4,5,9.77])
print(arrayint.dtype)
arrayint=arrayint.astype(int)
print(arrayint.dtype)

float64
int32


# Accessing Elements in an Array 

In [59]:
#NumPy Indexing and Slicing

array_ele=np.arange(6)
array_ele

array([0, 1, 2, 3, 4, 5])

In [60]:
array_ele[0] #first element

0

In [61]:
array_ele[-2] #last but one element

4

In [62]:
array_ele[::-1]  #Reversing the elements

array([5, 4, 3, 2, 1, 0])

In [63]:
#Accessing elements in a multidimensional array

array_ele2=np.array([[4,3],[3,5],[1,2]])
print(array_ele2)

[[4 3]
 [3 5]
 [1 2]]


In [64]:
array_ele2[0,1]=-1 #changing the values of the arrays
array_ele2

array([[ 4, -1],
       [ 3,  5],
       [ 1,  2]])

In [65]:
#Retrieve the first row:
array_ele2[1]  #Row elements starts from 0

array([3, 5])

In [66]:
#Retrieve 2nd row and all cols

array_ele2[2,:]

array([1, 2])

In [67]:
array_ele2[:1]

array([[ 4, -1]])

In [68]:
#Retrieve the columns

##arr[row:col] 
array_ele2[:,1]

array([-1,  5,  2])

In [ ]:
## default syntax for slicing=arr[row:col] 
#values before the, is for the rows and after the , is for the columns

In [69]:
arr_5=2*np.arange(10)
arr_5  #indexes only

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
arr_5[0:6:2] #0th index to 6th index

array([0, 4, 8])

In [71]:
arr_5[0:3] #0th index to 2nd index

array([0, 2, 4])

In [72]:
arr_5[3:] #3rd element to end

array([ 6,  8, 10, 12, 14, 16, 18])

In [73]:
arr_5[::3] #stepjumping by 3, Stride by 3 places

array([ 0,  6, 12, 18])

In [74]:
arr_5[1]=-2 #Replace one element
arr_5

array([ 0, -2,  4,  6,  8, 10, 12, 14, 16, 18])

In [75]:
arr_5[:3]=-2  #replacing all the elements until index 2 as -2
arr_5

array([-2, -2, -2,  6,  8, 10, 12, 14, 16, 18])

In [76]:
arr_5[2:]=np.ones(1)
arr_5

array([-2, -2,  1,  1,  1,  1,  1,  1,  1,  1])

In [77]:
arr_5[2:]=np.ones(8)
arr_5

array([-2, -2,  1,  1,  1,  1,  1,  1,  1,  1])

In [78]:
arr_5[2:]=np.ones(1)
arr_5

array([-2, -2,  1,  1,  1,  1,  1,  1,  1,  1])

In [79]:
#creating a 5X5 array

array5X5=np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45]])
array5X5

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [80]:
array5X5[0,3:5]

array([4, 5])

In [81]:
array5X5[4:,4:]

array([[45]])

In [82]:
array5X5[3:,2:]

array([[33, 34, 35],
       [43, 44, 45]])

In [83]:
array5X5[:,2]

array([ 3, 13, 23, 33, 43])

In [84]:
#starting the 2nd row in steps of two and respect to column skip by 2

array5X5[2::2,::2] 

array([[21, 23, 25],
       [41, 43, 45]])

In [85]:
#random number gen - to get the same set of random numbers everytime
np.random.seed(50)
arrayrandint=np.random.randint(25,50,5)
arrayrandint


array([41, 25, 36, 38, 26])

In [86]:
np.random.random(25.0,35.0)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [87]:
arfl=np.random.random(25)
arfl

array([0.60993813, 0.02143623, 0.15220072, 0.95470613, 0.80468256,
       0.24423009, 0.3251973 , 0.43930505, 0.13478847, 0.59472326,
       0.97821597, 0.08861251, 0.29394091, 0.23904398, 0.51661166,
       0.04597103, 0.26465872, 0.67136671, 0.78927019, 0.36441934,
       0.11342968, 0.16679188, 0.01824974, 0.78856948, 0.27714299])

In [88]:
np.random.seed(100)
arr69=np.random.randint(25,50,5)
arr69

array([33, 49, 28, 32, 48])

In [89]:
arr_even=(arrayrandint%2==0)
arr_even

array([False, False,  True,  True,  True])

In [90]:
arrayrandint[arr_even]

array([36, 38, 26])

In [91]:
##

arr_county=np.array(['India','Russia','France','','Srilanka'])
arr_county

array(['India', 'Russia', 'France', '', 'Srilanka'], dtype='<U8')

In [92]:
arr_county[arr_county == ''] = 'Pakistan'
arr_county

array(['India', 'Russia', 'France', 'Pakistan', 'Srilanka'], dtype='<U8')

In [93]:
#Masking the empty space with new values

arstate=np.array(['Assam','Karnataka','Delhi','','Chennai'])
print(arstate)
arstate[arstate == ''] = 'Bombay'
print(arstate)

['Assam' 'Karnataka' 'Delhi' '' 'Chennai']
['Assam' 'Karnataka' 'Delhi' 'Bombay' 'Chennai']


In [94]:
arr_county=np.array(['India','Russia','France','','Bhutan'])
arr_county
arr_county[arr_county == ''] = 'SouthAfrica'
arr_county

array(['India', 'Russia', 'France', 'SouthA', 'Bhutan'], dtype='<U6')

In [95]:
arr_county[[1,2,3]]

array(['Russia', 'France', 'SouthA'], dtype='<U6')

In [96]:
arr_county[[1,4]]

array(['Russia', 'Bhutan'], dtype='<U6')

In [97]:
arr_county[[1,4]]=100
arr_county

array(['India', '100', 'France', 'SouthA', '100'], dtype='<U6')

In [98]:
array5X5[0,-2]

4

In [99]:
#Complex indexing

arr_15=np.arange(20)
arr_15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [100]:
arr_16=np.arange(-11,-20,-1)[::-1]
arr_16

##[-11,-12,-13,-14,-,15,-16,-17,-18,-19]

array([-19, -18, -17, -16, -15, -14, -13, -12, -11])

In [101]:
arr_15[:9]=arr_16
arr_15

array([-19, -18, -17, -16, -15, -14, -13, -12, -11,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

# Copies and Views

In [16]:
arr_1=np.arange(5)
arr_2=arr_1[::2]
print(arr_1)
print(arr_2)

[0 1 2 3 4]
[0 2 4]


In [17]:
arr_2[1]=-4
arr_2

array([ 0, -4,  4])

In [18]:
arr_1

array([ 0,  1, -4,  3,  4])

In [ ]:
#arr2 will be referencing the values in the arr1. changes made to arr2 will reflect in arr1
#hence arr2 will be a view of arr1

In [19]:
arr_3=np.arange(10)
arr_3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr_4=arr_3[:3].copy()
arr_4

array([0, 1, 2])

In [107]:
arr_4[1]=-10
print(arr_3)
print(arr_4)

[0 1 2 3 4 5 6 7 8 9]
[  0 -10   2]


In [ ]:
#arr4 is a copy of arr3

# Basic Operations

In [22]:
#Basic Operation

arr_1=np.arange(1,10)*4  #Multiply
arr_1

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [21]:
#power operation

arr_2=np.arange(1,10)**2
arr_2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [110]:
#operations are performed element wise
arr_3=arr_1 * 0.5
arr_3

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [111]:
arr_4 = 4+np.arange(0,20,2)
arr_4

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [112]:
arr_5=np.arange(10)
arr_5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr_6=arr_4-arr_5
print(arr_6)

NameError: name 'arr_5' is not defined

In [28]:
arr_7=arr_5/arr_4
arr_7

NameError: name 'arr_5' is not defined

In [115]:
arr_8=arr_4*arr_5
arr_8

array([  0,   6,  16,  30,  48,  70,  96, 126, 160, 198])

In [116]:
arr_11=np.arange(100)
%timeit arr_11 * 3

1.2 µs ± 64.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [117]:
arr_12 = range(100)
%timeit [arr_12[i]** 3 for i in arr_12]

74.6 µs ± 3.75 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
#Matrix multiplication

arr_21=np.array([[5,2],[6,3]])
arr_22=np.array([[2,3],[4,5]])
arr_23=arr_21.dot(arr_22)      #.dot for multiplicative
arr_23

array([[18, 25],
       [24, 33]])

In [17]:
arr_21=np.array([[5,2],[6,3]])
arr_31=np.array([[8,7],[9,4]])
arr_23=arr_21.dot(arr_31)      #.dot for multiplicative
print(arr_21)
print(arr_31)
arr_23

[[5 2]
 [6 3]]
[[8 7]
 [9 4]]


array([[58, 43],
       [75, 54]])

In [18]:
#Logical operations

arr_25=arr_21<arr_31
arr_25

array([[ True,  True],
       [ True,  True]])

In [19]:
arr_26=arr_5>arr_4
arr_25

array([[ True,  True],
       [ True,  True]])

In [20]:
#logical
#And operation
arr_17 = np.array([True,False,True,False])
arr_18 = np.array([True,True,False,False])

arr_20 = np.logical_and(arr_17,arr_18)
arr_20

array([ True, False, False, False])

In [21]:
arr_21 = np.logical_or(arr_17,arr_18) #or operation
arr_21

array([ True,  True,  True, False])

In [22]:
arr_22 = np.array([np.pi,np.pi/2])
arr_22

array([3.14159265, 1.57079633])

In [23]:
arr_22=np.array([np.pi,np.pi/2])
arr_24=np.sin(arr_21)
print(arr_24)
arr_22

[0.8413 0.8413 0.8413 0.    ]


array([3.14159265, 1.57079633])

In [24]:
#arrays have to be of the same shape else, or they have to be broadcasted 

arr_31 = np.arange(1,6)
arr_32 = np.arange(1,8)
arr_33 = arr_31+arr_32


ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [25]:
#array equal function compares the shape and the elements of two arrays

arr_41 = np.arange(1,7)
arr_42 = np.array([1,2,3,4,5,6])  #comparing the shape and the elements to the given shape
arr_43 = np.array_equal(arr_41,arr_42)
arr_43

True

In [26]:
#Comparison for all elements

arr_44=np.all(arr_41==arr_42)
arr_44

True

In [27]:
arr_45=np.arange(1,10)
arr_45

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr_42

array([1, 2, 3, 4, 5, 6])

In [29]:
arr_50 = np.array([4,5,7,8])
arr_51 = np.array([9,3,2,6])
arr_46 = np.any(arr_50>arr_51)
arr_46

True

In [1]:
#Broadcasting one array into another

import numpy as np
arr_1 = np.ones([5,2])
arr_1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
arr_2 = np.array([5,2])
arr_2

array([5, 2])

In [4]:
arr_3 = arr_1 + arr_2 #arr2 is being broadcasted to arr1
arr_3

array([[6., 3.],
       [6., 3.],
       [6., 3.],
       [6., 3.],
       [6., 3.]])

In [6]:

arr_4=np.array([[11,22,33]])
arr_5=arr_4.T     #Transpose of an array
arr_5

array([[11],
       [22],
       [33]])

In [7]:
arr_6=arr_4+arr_5 
arr_6

array([[22, 33, 44],
       [33, 44, 55],
       [44, 55, 66]])

In [8]:
#reshaping a matrix

x=np.arange(4)
x

array([0, 1, 2, 3])

In [9]:
#convert 1x4 to 4x1
xx = x.reshape(4,1)
xx

array([[0],
       [1],
       [2],
       [3]])

In [10]:
y=np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [11]:
z= xx+y
z

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

# Array Manipulation & Array Sorting

In [5]:
#Create two arrays with any shape and try to 
import numpy as np
ary=np.array([[5,7],[4,5],[9,0]], dtype=int)
ary2=np.array([[3,6],[2,4],[1,8]], dtype=int)

In [7]:
ary3=ary.reshape(2,3)
print(ary)
ary3

[[5 7]
 [4 5]
 [9 0]]


array([[5, 7, 4],
       [5, 9, 0]])

In [10]:
#Resizing of Array
ary4=ary3
ary4.resize(6)
ary4

array([5, 7, 4, 5, 9, 0])

In [27]:
ary4=ary3
ary3.resize(8)
ary4

ValueError: cannot resize this array: it does not own its data

In [26]:
#Array resize

ary4=arr_2 
ary2.resize(8)  #if number of elements are less than 0s are appended
                #if a view is created then resize will not work
ary4               #reshape will not work for views in arrays

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [30]:
#Elements from the array are appended at the end when the array is passed as an argument
arr_6=np.arange(10,15)
arr_7=np.resize(arr_4,(8,))
arr_7

array([0, 1, 2, 0, 1, 2, 0, 1])

In [31]:
arr_4

array([0, 1, 2])

In [34]:
#flattening a multidimensional array
#ravel func : No of rows and columns need not to be known
arr_11 = np.array([np.arange(2,7), np.arange(15,20)])
print(arr_11)
arr_22=arr_11.flatten()
arr_22

[[ 2  3  4  5  6]
 [15 16 17 18 19]]


array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19])

In [35]:
#np.flatten(). Same as ravel function. returns a copy of the original array
arr_22=arr_11.ravel()
arr_22

array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19])

In [36]:
#adding a new dimension to an existing array
#number of elements is the shape of the array i.e (3,) becomes (3,3)
#Scalar matrix is a set of elements
arr_9=np.array([21,22,23],[24,25,26])
print(arr_9.shape)
arr_10 = arr_9[:, np.newaxis]
print(arr_10)
arr_10.shape

(3,)
[[21]
 [22]
 [23]]


(3, 1)

In [39]:
arr_11=arr_10[:,np.newaxis]
print(arr_11.shape)
arr_11

(3, 1, 1)


array([[[21]],

       [[22]],

       [[23]]])

In [40]:
arr_22=np.array([[1,2],[2,3]])
print(arr_22)
arr_21=arr_22[:, np.newaxis]
arr_21

[[1 2]
 [2 3]]


array([[[1, 2]],

       [[2, 3]]])

In [41]:
#Array Sorting

arr_12=np.array([[4,5,2],[3,2,1]])
arr_12.sort(axis=1)   # 1 is row wise or x axis
arr_12

array([[2, 4, 5],
       [1, 2, 3]])

In [42]:
arr_12=np.array([[4,5,2],[3,2,1]])
arr_12.sort(axis=0) #0 is column wise or y axis
arr_12

array([[3, 2, 1],
       [4, 5, 2]])

In [43]:
?np.sort

In [44]:
#Reduction and statistical operations
#product of all elements
arr_30=np.arange(1,8)
arr_30.prod()

5040

In [45]:
arr_31=np.array([[np.arange(2,6),np.arange(2,6)]])
arr_31

array([[[2, 3, 4, 5],
        [2, 3, 4, 5]]])

In [50]:
arr_32=np.prod(arr_31, axis=0)
print(arr_31.shape)
arr_32


(2, 4)


array([ 4,  9, 16, 25])

In [48]:
arr_32=np.prod(arr_31, axis=1)
arr_32

array([120, 120])

In [ ]:
#np.mean,#np.median,#np.sum