In [1]:
import numpy as np

In [2]:
#create a single dimensional array
array_1=np.array([11,22,33,44,55,66]) #accepts only homogenous datatype
array_1

array([11, 22, 33, 44, 55, 66])

In [3]:
type(array_1)

numpy.ndarray

In [4]:
array_1.dtype

dtype('int32')

In [5]:
array_1[-2]

55

In [7]:
array_1.shape

(6,)

In [8]:
#create an array using two lists

array_1=np.array([[11,22,33,44,55,66],[77,88,99,12,34,56]])
array_1

array([[11, 22, 33, 44, 55, 66],
       [77, 88, 99, 12, 34, 56]])

In [9]:
type(array_1)

numpy.ndarray

In [10]:
array_1.shape

(2, 6)

In [16]:
#to check n number of dimensions
array_1.ndim

2

In [11]:
array_1[1][4]

34

In [12]:
#create a numpy array using arange function
array_3=np.arange(5)
array_3

array([0, 1, 2, 3, 4])

In [13]:
#Using same function, create two dimensional array, and then use indexing 

array_3=np.array([np.arange(5),np.arange(6,11)])[1,3]
array_3

9

In [14]:
#Linspace function
array_4 = np.linspace(0,1,10)
array_4

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
##ones matrix
array_5 = np.ones((3,4))
array_5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
##zeroes matrix
array_6 = np.zeros((3,4))
array_6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
#to create an identity matrix
array_7=np.eye(4)
array_7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#to create a diagonal matrix
array_8=np.diag((1,2,3,4))
array_8

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
#create a random number
array_9 = np.random.rand(4)
array_9

array([0.6167974 , 0.25756575, 0.97759314, 0.16886115])

In [20]:
array_10 = np.random.rand(4,2)
array_10

array([[0.62232606, 0.60013105],
       [0.9278684 , 0.52386419],
       [0.9609936 , 0.69947282],
       [0.93069499, 0.37231103]])

In [22]:
array_11 = np.random.randn(5)
array_11

array([ 0.56973618, -1.54575724,  0.85813913, -0.20416497, -1.81589357])

In [23]:
array_11 = np.random.randn(3,4)
array_11

array([[-0.38996006,  1.61130642,  0.39361822, -1.17701938],
       [-0.26411797, -0.28305319, -2.15229688, -0.22326372],
       [ 0.89966512,  0.27021428,  1.4838672 ,  0.2766857 ]])

In [26]:
array_12=np.random.randint(1,5,10)
array_12

array([3, 4, 2, 3, 3, 3, 1, 2, 4, 3])

In [27]:
array_13 = np.empty((4,3))
array_13

array([[0.38996006, 1.61130642, 0.39361822],
       [1.17701938, 0.26411797, 0.28305319],
       [2.15229688, 0.22326372, 0.89966512],
       [0.27021428, 1.4838672 , 0.2766857 ]])

In [28]:
#create an array using tile function

array_14=np.tile(([5,3],[8,9]),3)
array_14

array([[5, 3, 5, 3, 5, 3],
       [8, 9, 8, 9, 8, 9]])

In [29]:
#create ana
x=np.array([1,2,3,4])
np.tile(x,3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [30]:
#datatype declaration while creating array. suppose you are using integer value to explicitly

array_15=np.array([4,-2,5.6,9],dtype=float)
array_15

array([ 4. , -2. ,  5.6,  9. ])

In [31]:
array_16=np.array([4,2,-9,8], dtype=int)
array_16

array([ 4,  2, -9,  8])

In [32]:
#to create a string array
np.array(['hello','hi','how are you'])

array(['hello', 'hi', 'how are you'], dtype='<U11')

In [33]:
#convert array to a desired datatype

x.astype(float)

array([1., 2., 3., 4.])

In [34]:
#create an array
array_18 = np.array(([4,3],[3,5],[1,2]))
array_18

array([[4, 3],
       [3, 5],
       [1, 2]])

In [35]:
#changing the values of the arrays
array_18[1,1]=-1
array_18

array([[ 4,  3],
       [ 3, -1],
       [ 1,  2]])

In [36]:
#create an array with arange function and multiply the value with 5

array_19=5*np.arange(10)
array_19

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [37]:
#slice every 3 elements
array_19[0:8:3]

array([ 0, 15, 30])

In [39]:
#create single dimensional array and populate each value by 1 after 3
array_19[3:]=np.ones(1)
array_19

array([ 0,  5, 10,  1,  1,  1,  1,  1,  1,  1])

In [40]:
#using random integer function create 5 random numbers within 20 to 50 then find the even numbers

array_20 = np.random.randint(25,50,5)
array_20

array([33, 40, 31, 28, 25])

In [41]:
array_20[array_20%2==0]

array([40, 28])

In [42]:
array_21=np.array([[5,7],[4,5],[9,0]], dtype=int)
array_22=np.array([[3,6],[2,4],[1,8]], dtype=int)

In [43]:
array_23=array_21.reshape(2,3)
print(array_23)
array_23

[[5 7 4]
 [5 9 0]]


array([[5, 7, 4],
       [5, 9, 0]])

In [44]:
#using ravel() function

array_24=np.array([np.arange(2,7), np.arange(15,20), np.arange(25,30)])
print(array_24)
array_25=array_24.ravel()
array_25

[[ 2  3  4  5  6]
 [15 16 17 18 19]
 [25 26 27 28 29]]


array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29])

In [45]:
array_25=array_24.flatten()
array_25

array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29])

In [46]:
#create a 2D array or 3D array using the existing array

array_25=array_24[:, np.newaxis]
array_25

array([[[ 2,  3,  4,  5,  6]],

       [[15, 16, 17, 18, 19]],

       [[25, 26, 27, 28, 29]]])

In [47]:
array_25.shape

(3, 1, 5)

In [48]:
#Array Sorting

array_26=np.array([[4,5,2],[3,2,1]])
array_26.sort(axis=1)   # 1 is col wise or x axis
array_26

array([[2, 4, 5],
       [1, 2, 3]])

In [49]:
#row wise
array_26=np.array([[4,5,2],[3,2,1]])
array_26.sort(axis=0)   # 0 is row wise or y axis
array_26

array([[3, 2, 1],
       [4, 5, 2]])

In [50]:
#Reduction and statistical operation
array_27=np.arange(1,8)
array_27.prod()

5040

In [51]:
array_26.prod()

240

In [52]:
arr_31=np.array([[np.arange(2,6),np.arange(2,6)]])
arr_31

array([[[2, 3, 4, 5],
        [2, 3, 4, 5]]])

In [53]:
arr_32=np.prod(arr_31, axis=0)
print(arr_31.shape)
arr_32

(1, 2, 4)


array([[2, 3, 4, 5],
       [2, 3, 4, 5]])

In [54]:
arr_32 = np.prod(arr_31, axis=1)
arr_32

array([[ 4,  9, 16, 25]])

# Pandas

In [55]:
import pandas as pd
pd.__version__

'0.23.4'

In [56]:
#pandas is built on the top of numpy panda can be work on heterogenous data
#take a variable and create series
x = pd.Series([1,2,3,4], index=["hong","dong","gondar","gomensai"])
x



hong        1
dong        2
gondar      3
gomensai    4
dtype: int64

In [57]:
x.index=["a","b","c","d"]
x

a    1
b    2
c    3
d    4
dtype: int64

In [58]:
#create a dictionary with 4 keys, city_name each value will be city pincode and then create a series

dict1={"Guwahati":781021,"Bihar":194564,"Gurgaon": 223456,"Bengaluru":400227}
series1 = pd.Series(dict1)
series1

Guwahati     781021
Bihar        194564
Gurgaon      223456
Bengaluru    400227
dtype: int64

In [59]:
series1["Bihar":"Gurgaon"]

Bihar      194564
Gurgaon    223456
dtype: int64

In [60]:
series1[:1]

Guwahati    781021
dtype: int64

In [61]:
series1['Guwahati']='Assam'

In [62]:
series1

Guwahati      Assam
Bihar        194564
Gurgaon      223456
Bengaluru    400227
dtype: object

In [63]:
series1['Guwahati']=781021

In [64]:
series1

Guwahati     781021
Bihar        194564
Gurgaon      223456
Bengaluru    400227
dtype: object

In [65]:
series1[:1]='Assam'
series1

Guwahati      Assam
Bihar        194564
Gurgaon      223456
Bengaluru    400227
dtype: object

In [66]:
series1.index=['Assam','Bihar','Gurgaon','Bengaluru']
series1

Assam         Assam
Bihar        194564
Gurgaon      223456
Bengaluru    400227
dtype: object

In [67]:
series2=pd.DataFrame(series1)
series2

0
Assam       Assam
Bihar      194564
Gurgaon    223456
Bengaluru  400227

In [68]:
series2.columns=['Pincode']
series2

Pincode
Assam       Assam
Bihar      194564
Gurgaon    223456
Bengaluru  400227

In [69]:
dict2={"Rahul":9435109405,"Karthick":9008765342,"Iftikar":9365656454,"Jasmin":7896756893}
series3=pd.Series(dict2)
series3



Rahul       9435109405
Karthick    9008765342
Iftikar     9365656454
Jasmin      7896756893
dtype: int64

In [70]:
series4=pd.DataFrame(series3)
series4

0
Rahul     9435109405
Karthick  9008765342
Iftikar   9365656454
Jasmin    7896756893

In [71]:
series4.columns=['Phone Number']
series4

Phone Number
Rahul       9435109405
Karthick    9008765342
Iftikar     9365656454
Jasmin      7896756893

In [72]:
#creating a series
dict1 = {"Google": 450, "Amazon": 1200, "Yes Bank": 6004, "Flipkart": 1099, "Jabong": 892}
series1 = pd.Series(dict1)
series1

Google       450
Amazon      1200
Yes Bank    6004
Flipkart    1099
Jabong       892
dtype: int64

In [73]:
series1.index

Index(['Google', 'Amazon', 'Yes Bank', 'Flipkart', 'Jabong'], dtype='object')

In [74]:
series1.index.sort_values()

Index(['Amazon', 'Flipkart', 'Google', 'Jabong', 'Yes Bank'], dtype='object')

In [75]:
ex1={'b':33,'D':53,'a':23,'c':43}
series2=pd.Series(ex1)
series2

b    33
D    53
a    23
c    43
dtype: int64

In [76]:
ex1={'b':033.00,'D':53.1,'a':23.5,'c':43.2}
series2 = pd.Series(ex1)
series2

b    33.0
D    53.1
a    23.5
c    43.2
dtype: float64

In [77]:
st1 = {'INFY':567.12,'TCS':345.34,'Wipro': 564.45, 'HCL':45.15,'L&T':678.00}
ser2 = pd.Series(st1, index = ['Wipro','TCS','HCL','L&T','INFY'])
ser2

Wipro    564.45
TCS      345.34
HCL       45.15
L&T      678.00
INFY     567.12
dtype: float64

In [78]:
ser2.index

Index(['Wipro', 'TCS', 'HCL', 'L&T', 'INFY'], dtype='object')

In [80]:
#Operations on series

ser2[0]=1000

In [81]:
ser2

Wipro    1000.00
TCS       345.34
HCL        45.15
L&T       678.00
INFY      567.12
dtype: float64

In [82]:
ser2['Genpact']

KeyError: 'Genpact'

In [83]:
ser2[:3]  #upper values of the dictionary

Wipro    1000.00
TCS       345.34
HCL        45.15
dtype: float64

In [84]:
ser2.tail(2) #lower values of the dictionary

L&T     678.00
INFY    567.12
dtype: float64

In [85]:
#Logical Operations
ex2=series1[series1>500]
ex2

Amazon      1200
Yes Bank    6004
Flipkart    1099
Jabong       892
dtype: int64

In [86]:
np.mean(ser2)

527.122

In [87]:
ser2.mean()

527.122

In [88]:
##
arr1 = np.array([1,2,3,4,5,6,7])
ser3=pd.Series(arr1)

In [89]:
ser3

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [91]:
ser4 = ser3*ser3
ser4

0     1
1     4
2     9
3    16
4    25
5    36
6    49
dtype: int32

In [93]:
np.sqrt(ser4)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
dtype: float64

In [94]:
ser4[:-1]

0     1
1     4
2     9
3    16
4    25
5    36
dtype: int32

In [95]:
ser4[1:]

1     4
2     9
3    16
4    25
5    36
6    49
dtype: int32

In [96]:
b=ser4[:-1]
b

0     1
1     4
2     9
3    16
4    25
5    36
dtype: int32

In [99]:
a=ser4[1:]
series5=a+b
series5

0     NaN
1     8.0
2    18.0
3    32.0
4    50.0
5    72.0
6     NaN
dtype: float64

In [100]:
type(series5)

pandas.core.series.Series

In [101]:
#Dataframe Creation

series1 = {'INFY': pd.Series([1,2,3,4,5,6,7]), 'TCS': pd.Series([4,5,6,7,8,9,10]), 'Wipro': pd.Series([12,34,45,56,67,78,89])}
type(series1)

dict

In [102]:
series2=pd.DataFrame(series1)
series2

INFY  TCS  Wipro
0     1    4     12
1     2    5     34
2     3    6     45
3     4    7     56
4     5    8     67
5     6    9     78
6     7   10     89

In [103]:
series2.index

RangeIndex(start=0, stop=7, step=1)

In [104]:
series2.columns

Index(['INFY', 'TCS', 'Wipro'], dtype='object')

In [105]:
series2.T #transpose of the given dataframe

0   1   2   3   4   5   6
INFY    1   2   3   4   5   6   7
TCS     4   5   6   7   8   9  10
Wipro  12  34  45  56  67  78  89

In [106]:
#Dictionary of lists creating dataframe

st1 = {'INFY':[22,33,44,55,66,77], 'TCS':[22,33,44,55,66,77], 'Wipro': [22,33,44,55,66,77], 'HCL': [22,33,44,55,66,77], 'L&T': [22,33,44,55,66,77]}
st1

{'INFY': [22, 33, 44, 55, 66, 77],
 'TCS': [22, 33, 44, 55, 66, 77],
 'Wipro': [22, 33, 44, 55, 66, 77],
 'HCL': [22, 33, 44, 55, 66, 77],
 'L&T': [22, 33, 44, 55, 66, 77]}

In [107]:
pd.DataFrame(st1)

INFY  TCS  Wipro  HCL  L&T
0    22   22     22   22   22
1    33   33     33   33   33
2    44   44     44   44   44
3    55   55     55   55   55
4    66   66     66   66   66
5    77   77     77   77   77

In [108]:
##Using structured array

df3= np.zeros((4,), dtype=[('Name','U25'),('Gender','U10'),('Present/Absent','U15')])
df3

array([('', '', ''), ('', '', ''), ('', '', ''), ('', '', '')],
      dtype=[('Name', '<U25'), ('Gender', '<U10'), ('Present/Absent', '<U15')])

In [109]:
df3[:]= [('Ram','Male','Present'), ('Joseph','Male','Absent'),('Priya','Female','Absent'),('Swetha','Female','Present')]
df3

array([('Ram', 'Male', 'Present'), ('Joseph', 'Male', 'Absent'),
       ('Priya', 'Female', 'Absent'), ('Swetha', 'Female', 'Present')],
      dtype=[('Name', '<U25'), ('Gender', '<U10'), ('Present/Absent', '<U15')])

In [110]:
df4=pd.DataFrame(df3)
df4

Name  Gender Present/Absent
0     Ram    Male        Present
1  Joseph    Male         Absent
2   Priya  Female         Absent
3  Swetha  Female        Present

In [111]:
#creating a data frame from a series
st1 = {'INFY':567.12,'TCS':345.34,'Wipro': 564.45, 'HCL':45.15,'L&T':678.00}
ser2 = pd.Series(st1, index = ['Wipro','TCS','HCL','L&T','INFY'])
ser2

Wipro    564.45
TCS      345.34
HCL       45.15
L&T      678.00
INFY     567.12
dtype: float64

In [112]:
df6 = pd.DataFrame(ser2)
df6

0
Wipro  564.45
TCS    345.34
HCL     45.15
L&T    678.00
INFY   567.12

In [113]:
st1 = {'INFY':700.90,'TCS':600.99,'Wipro': 500.64, 'HCL':400.33,'L&T':678.00}
ser5 = pd.Series(st1, index = ['Wipro','TCS','HCL','L&T','INFY'])
ser5

Wipro    500.64
TCS      600.99
HCL      400.33
L&T      678.00
INFY     700.90
dtype: float64

In [114]:
df6=pd.DataFrame(ser2+ser5)
df6

0
Wipro  1065.09
TCS     946.33
HCL     445.48
L&T    1356.00
INFY   1268.02

In [115]:
serfin=pd.concat([ser2,ser5], axis=1)
serfin

0       1
Wipro  564.45  500.64
TCS    345.34  600.99
HCL     45.15  400.33
L&T    678.00  678.00
INFY   567.12  700.90

In [116]:
df7=pd.DataFrame(serfin)
df7

0       1
Wipro  564.45  500.64
TCS    345.34  600.99
HCL     45.15  400.33
L&T    678.00  678.00
INFY   567.12  700.90

In [117]:
df7.columns

RangeIndex(start=0, stop=2, step=1)

In [118]:
df7.columns = ['day1','day2']
df7

day1    day2
Wipro  564.45  500.64
TCS    345.34  600.99
HCL     45.15  400.33
L&T    678.00  678.00
INFY   567.12  700.90

In [119]:
df7[:2]

day1    day2
Wipro  564.45  500.64
TCS    345.34  600.99

In [120]:
x1=df7['day1']
x1

Wipro    564.45
TCS      345.34
HCL       45.15
L&T      678.00
INFY     567.12
Name: day1, dtype: float64

In [121]:
df7['day1']['TCS'] = 1966
df7

day1    day2
Wipro   564.45  500.64
TCS    1966.00  600.99
HCL      45.15  400.33
L&T     678.00  678.00
INFY    567.12  700.90

In [122]:
df7.insert(2,'day3',(500,400,300,200,100))
df7

day1    day2  day3
Wipro   564.45  500.64   500
TCS    1966.00  600.99   400
HCL      45.15  400.33   300
L&T     678.00  678.00   200
INFY    567.12  700.90   100

In [127]:
##Basic Indexing

oil_data = {'France' : {'2015-Q1': 100.1,'2015-Q2': 104.6, '2015-Q3': 400, '2025-Q4': 340},
            'Germany' : {'2015-Q1': 110.1,'2015-Q2': 156.6, '2015-Q3': 250, '2025-Q4': 270},                                                                             
            'Poland' : {'2015-Q1': 99.0,'2015-Q2': 103.6, '2015-Q3': 105.7, '2025-Q4': 450},
           }
oil_data

{'France': {'2015-Q1': 100.1,
  '2015-Q2': 104.6,
  '2015-Q3': 400,
  '2025-Q4': 340},
 'Germany': {'2015-Q1': 110.1,
  '2015-Q2': 156.6,
  '2015-Q3': 250,
  '2025-Q4': 270},
 'Poland': {'2015-Q1': 99.0,
  '2015-Q2': 103.6,
  '2015-Q3': 105.7,
  '2025-Q4': 450}}

In [128]:
oil_df=pd.DataFrame.from_dict(oil_data)
oil_df

France  Germany  Poland
2015-Q1   100.1    110.1    99.0
2015-Q2   104.6    156.6   103.6
2015-Q3   400.0    250.0   105.7
2025-Q4   340.0    270.0   450.0

In [129]:
France_data = oil_df['France']
France_data

2015-Q1    100.1
2015-Q2    104.6
2015-Q3    400.0
2025-Q4    340.0
Name: France, dtype: float64

In [130]:
#order of the coloumns in a different way

oil_df[['Poland','Germany','France']]

Poland  Germany  France
2015-Q1    99.0    110.1   100.1
2015-Q2   103.6    156.6   104.6
2015-Q3   105.7    250.0   400.0
2025-Q4   450.0    270.0   340.0

In [131]:
oil_df['France'] #oil_df_France

2015-Q1    100.1
2015-Q2    104.6
2015-Q3    400.0
2025-Q4    340.0
Name: France, dtype: float64

In [132]:
oil_df[::-1]

France  Germany  Poland
2025-Q4   340.0    270.0   450.0
2015-Q3   400.0    250.0   105.7
2015-Q2   104.6    156.6   103.6
2015-Q1   100.1    110.1    99.0

In [133]:
##label  -oriented indexing

snow_data = {'Months': ['January','February','March','April','May','June'],
            'Avg low temp': [26,34,25,45,23,21],
            'Avg precip' : [17.8,12.3,11.7,34.0,12.3,11.5],
             'Avg snowdays' : [3.0,6.0,5.0,2.0,3.3,4.5]}

In [134]:
snow_df = pd.DataFrame(snow_data, index = snow_data['Months'], columns = ['Avg low temp','Avg precip','Avg snowdays'])
snow_df

Avg low temp  Avg precip  Avg snowdays
January             26        17.8           3.0
February            34        12.3           6.0
March               25        11.7           5.0
April               45        34.0           2.0
May                 23        12.3           3.3
June                21        11.5           4.5

In [135]:
snow_df.loc[['January','June']]

Avg low temp  Avg precip  Avg snowdays
January            26        17.8           3.0
June               21        11.5           4.5

In [139]:
#Basic indexing syntax
snow_df.loc[:,'Avg low temp']

January     26
February    34
March       25
April       45
May         23
June        21
Name: Avg low temp, dtype: int64

In [140]:
snow_df.loc['March','Avg low temp']

25

In [141]:
snow_df.loc['March']['Avg low temp'] #the row will be first then the column

25.0

In [143]:
snow_df['Avg low temp']['March'] #without .loc, the col will be the first then the row

25

In [144]:
oil_df

France  Germany  Poland
2015-Q1   100.1    110.1    99.0
2015-Q2   104.6    156.6   103.6
2015-Q3   400.0    250.0   105.7
2025-Q4   340.0    270.0   450.0

In [145]:
#Select all the rows where 2015-Q1>100. Get only those values

oil_df.where(oil_df[:1]>100)

France  Germany  Poland
2015-Q1   100.1    110.1     NaN
2015-Q2     NaN      NaN     NaN
2015-Q3     NaN      NaN     NaN
2025-Q4     NaN      NaN     NaN

In [146]:
#getting relevant values
oil_df.loc[:, oil_df.loc['2015-Q1'] > 100]

France  Germany
2015-Q1   100.1    110.1
2015-Q2   104.6    156.6
2015-Q3   400.0    250.0
2025-Q4   340.0    270.0

In [147]:
oil_df.loc['2015-Q1'][["France","Germany"]]

France     100.1
Germany    110.1
Name: 2015-Q1, dtype: float64

In [148]:
oil_df.describe().transpose() #to find out the statistical methods of oil_df dataframe

count     mean         std    min      25%     50%      75%    max
France     4.0  236.175  156.467939  100.1  103.475  222.30  355.000  400.0
Germany    4.0  196.675   75.985410  110.1  144.975  203.30  255.000  270.0
Poland     4.0  189.575  173.639212   99.0  102.450  104.65  191.775  450.0

In [149]:
#Integer -- oriented indexing
z = {'x': [1,2,3,4,5], 'y':[11,12,13,14,15], 'z':[21,22,23,24,25]}
z

{'x': [1, 2, 3, 4, 5], 'y': [11, 12, 13, 14, 15], 'z': [21, 22, 23, 24, 25]}

In [150]:
x1=pd.DataFrame(z, index = list(range(0,10,2)))
x1

x   y   z
0  1  11  21
2  2  12  22
4  3  13  23
6  4  14  24
8  5  15  25

In [151]:
x1.iloc[:4]

x   y   z
0  1  11  21
2  2  12  22
4  3  13  23
6  4  14  24

In [152]:
x1.iloc[2,0:2]

x     3
y    13
Name: 4, dtype: int64

In [153]:
x1.loc[[4]] #x1.loc[4]

x   y   z
4  3  13  23

In [154]:
x1.iat[3,0]

4

In [155]:
%timeit x1.iloc[3,0]

The slowest run took 5.24 times longer than the fastest. This could mean that an intermediate result is being cached.
16.5 µs ± 13.2 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [156]:
#Boolean Indexing

stock_prices=pd.read_csv("D:/Manipal Data Science/First Term/NumPy/stock_index_prices.csv")
stock_prices

TradingDate PriceType   Nasdaq  S&P 500  Russell 2000
0   2014/02/21      open  4282.17  1841.07       1166.25
1   2014/02/21     close  4263.41  1836.25       1164.63
2   2014/02/21      high  4284.85  1846.13       1168.43
3   2014/02/24      open  4273.32  1836.78       1166.74
4   2014/02/24     close  4292.97  1847.61       1174.55
5   2014/02/24      high  4311.13  1858.71       1180.29
6   2014/02/25      open  4298.48  1847.66       1176.00
7   2014/02/25     close  4287.59  1845.12       1173.95
8   2014/02/25      high  4307.51  1852.91       1179.43
9   2014/02/26      open  4300.45  1845.79       1176.11
10  2014/02/26     close  4292.06  1845.16       1181.72
11  2014/02/26      high  4316.82  1852.65       1188.06
12  2014/02/27      open  4291.47  1844.90       1179.28
13  2014/02/27     close  4318.93  1854.29       1187.94
14  2014/02/27      high  4322.46  1854.53       1187.94
15  2014/02/28      open  4323.52  1855.12       1189.19
16  2014/02/28     close  4308.12  1859.45       1183.03
17  2014/02/28      high  4342.59  1867.92       1193.50

In [157]:
stock_prices.loc[(stock_prices.Nasdaq<4300)  & (stock_prices.PriceType == "high")]

TradingDate PriceType   Nasdaq  S&P 500  Russell 2000
2  2014/02/21      high  4284.85  1846.13       1168.43

In [158]:
stock_prices.loc[(stock_prices.Nasdaq>4300) & (stock_prices.PriceType == "close")]

TradingDate PriceType   Nasdaq  S&P 500  Russell 2000
13  2014/02/27     close  4318.93  1854.29       1187.94
16  2014/02/28     close  4308.12  1859.45       1183.03